export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_FAILURE = "PROFILE_FAILURE";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_UPDATE_USER = "PROFILE_UPDATE_USER";
export const PROFILE_CLEAR_MESSAGE = "PROFILE_CLEAR_MESSAGE";
export const PROFILE_SIGNOUT = "PROFILE_SIGNOUT";
