export const NOTIFICATION_UNREAD = "NOTIFICATION_UNREAD";
export const NOTIFICATION_INCREASE = "NOTIFICATION_INCREASE";
export const NOTIFICATION_DECREASE = "NOTIFICATION_DECREASE";
export const NOTIFICATION_NEW = "NOTIFICATION_NEW";

export const NOTIFICATION_CLEAR = "NOTIFICATION_CLEAR";
export const NOTIFICATION_RESET = "NOTIFICATION_RESET";
