export const NOTIFICATION_UNREAD = "NOTIFICATION_UNREAD";
export const NOTIFICATION_INCREASE = "NOTIFICATION_INCREASE";
export const NOTIFICATION_DECREASE = "NOTIFICATION_DECREASE";
export const NOTIFICATION_CLEAR = "NOTIFICATION_CLEAR";
