export const PERSONAL_PROFILE_REQUEST = "PERSONAL_PROFILE_REQUEST";
export const PERSONAL_PROFILE_FAILURE = "PERSONAL_PROFILE_FAILURE";
export const PERSONAL_PROFILE_SUCCESS = "PERSONAL_PROFILE_SUCCESS";
export const PERSONAL_PROFILE_CLEAR = "PERSONAL_PROFILE_CLEAR";
export const PROFILE_POSTS_INCREASE = "PROFILE_POSTS_INCREASE";
export const PROFILE_POSTS_DECREASE = "PROFILE_POSTS_DECREASE";
export const PROFILE_FOLLOWED_BY_INCREASE = "PROFILE_FOLLOWED_BY_INCREASE";
export const PROFILE_FOLLOWED_BY_DECREASE = "PROFILE_FOLLOWED_BY_DECREASE";
