export const PERSONAL_PROFILE_REQUEST = "PERSONAL_PROFILE_REQUEST";
export const PERSONAL_PROFILE_FAILURE = "PERSONAL_PROFILE_FAILURE";
export const PERSONAL_PROFILE_SUCCESS = "PERSONAL_PROFILE_SUCCESS";
export const PERSONAL_PROFILE_CLEAR = "PERSONAL_PROFILE_CLEAR";
